name: Deployment

on:
    workflow_dispatch:


jobs:
    deployment:
        runs-on: ubuntu-latest

        steps: 
            - name: Pull
              uses: actions/checkout@v4

            - name: K3S
              run: |
               wget -qO- https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
          
          
               k3d cluster create ml-cluster
              
            - name: Image Pull
              run: |
                docker build -t ml-api:local .
                k3d image tage ml-api:local ml-api:local -c ml-cluster || k3d image import ml-api:local -c ml-cluster
            
            - name: Manifest
              run: |
               sed -i 's|image: .*|image: ml-api:local|g' manifest.yaml
               kubectl apply -f manifest.yaml

            - name: Check k8s
              run: |
               kubectl rollout status deployment/ml-api-deployment --timeout=90s
               kubectl get pods -o wide
               kubectl get svc
            - name: Test
              run: |
               kubectl port-forward svc/ml-api-service 8000:8000 &
               sleep 3

               curl -f http://localhost:8000/healthz

               curl -f -X POST http://localhost:8000/predict \
                -H "Content-Type: application/json" \
                -d '{"feature_1":2.5, "feature_2" : 3.0}'