name: Docker pytest

on:
    workflow_dispatch:

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Docker Build
              run: docker build -t fastapi-test:latest .

            - name: Run Container
              run: docker run --rm fastapi-test:latest pytest -v