name: Python Code Quality

on:
    workflow_dispatch:
        inputs:
            debug_mode:
                description: "Czy włączyć tryb debugowania"
                required: false
                type: boolean
                default: false
jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: Code pull
              uses: actions/checkout@v4

            - name: Requirements
              run: |
                cat << 'EOF' > requirements.txt
                ruff
                fastapi
                pytest
                EOF

            - name: Prepare Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
                cache: 'pip'

            - name: Linter installation
              run: pip install ruff

            - name: Run static scan
              run: ruff check . 